# print('-23'.isidentifier())           
# print('ABC'.isidentifier())
# print('1-3'.isidentifier())
# print('F_I@G HT'.isidentifier())
# print('123 4'.isidentifier())
# print('HEI-GHT'.isidentifier())
# print('_256A'.isidentifier())
# print('@KL234'.isidentifier())
# print('HN$'.isidentifier())
# print('_45689'.isidentifier())